/**
 *
 * @author keyy/1501718947@qq.com 16/11/8 17:34
 * @description
 */
//初始化APP
export const APP_INITIAL_BEGIN='APP_INITIAL_BEGIN';
export const APP_INITIAL_END='APP_INITIAL_END';

//注册时获取短信验证码
export const FETCH_VALID_CODE='FETCH_VALID_CODE';
export const RECEIVE_VALID_CODE = 'RECEIVE_VALID_CODE';

//注册时验证短信验证码
export const VALID_CODE_BEGIN='VALID_CODE_BEGIN';
export const VALID_CODE_END='VALID_CODE_END';

//获取注册用户初始信息
export const FETCH_USER_PROFILE='FETCH_USER_PROFILE';
export const RECEIVE_USER_PROFILE='RECEIVE_USER_PROFILE';

//保存注册用户信息
export const FETCH_SAVE_USER_PROFILE='FETCH_SAVE_USER_PROFILE';
export const RECEIVE_SAVE_USER_PROFILE='RECEIVE_SAVE_USER_PROFILE';

//设置照片权限
export const SET_PERMISSION='SET_PERMISSION';

//拍照
export const TAKE_PHOTO='TAKE_PHOTO';
export const DELETE_PHOTO='DELETE_PHOTO';
export const SET_AS_AVATAR='SET_AS_AVATAR';

//下载照片
export const DOWNLOAD_IMAGE_BEGIN='DOWNLOAD_IMAGE_BEGIN';
export const DOWNLOAD_IMAGE_END='DOWNLOAD_IMAGE_END';

//上传照片
export const UPLOAD_PHOTO_BEGIN='UPLOAD_PHOTO_BEGIN';
export const UPLOAD_PHOTO_END='UPLOAD_PHOTO_END';
export const UPLOAD_PHOTO_FAILED='UPLOAD_PHOTO_FAILED';

//保存用户交友要求
export const UPDATE_FRIEND_FILTER_BEGIN='UPDATE_FRIEND_FILTER_BEGIN';
export const UPDATE_FRIEND_FILTER_END='UPDATE_FRIEND_FILTER_END';

//保存用户坐标
export const SAVE_USER_COORDINATE_BEGIN='SAVE_USER_COORDINATE_BEGIN';
export const SAVE_USER_COORDINATE_END='SAVE_USER_COORDINATE_END';

//获取附近用户
export const FETCH_USER_NEARBY='FETCH_USER_NEARBY';
export const RECEIVE_USER_NEARBY='RECEIVE_USER_NEARBY';

//获取附近用户详细信息
export const FETCH_USER_DETAIL_INFO='FETCH_USER_DETAIL_INFO';
export const RECEIVE_USER_DETAIL_INFO='RECEIVE_USER_DETAIL_INFO';

//通用请求
export const FETCH_BEGIN='FETCH_BEGIN';
export const FETCH_END='FETCH_END';
export const FETCH_FAILED='FETCH_FAILED';

//通用静默请求
export const FETCH_BEGIN_QUIET='FETCH_BEGIN_QUIET';
export const FETCH_END_QUIET='FETCH_END_QUIET';
export const FETCH_FAILED_QUIET='FETCH_FAILED_QUIET';

//从缓存中获取数据
export const GET_ITEM_BEGIN='GET_ITEM_BEGIN';
export const GET_ITEM_END='GET_ITEM_END';
export const GET_ITEM_FAILED='GET_ITEM_FAILED';




